spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tma_warehouse
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      root: INFO
      com.example.tma_warehouse.controllers.administrator: DEBUG

  flyway:
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 169491545934-2ci0s9tso6sru6ki52qtabo4422o71gu.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
